name: deployment-pipline
run-name: Deploy to ${{ github.deploy_target }} by @${{ github.actor }}

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs: 
    deploying:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
        - run: echo "Deploying code!"




